apiVersion: v1
kind: Service
metadata:
  name: {{ include "airlabs-poller.fullname" . }}
  labels:
    {{- include "airlabs-poller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.metricsPort }}
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "airlabs-poller.selectorLabels" . | nindent 4 }}
