apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- if .Values.httpPort }}
    - port: {{ .Values.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    {{- if .Values.metricsPort }}
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
